name: Create Release

on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
 
jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:        
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Github Release
          uses: elgohr/Github-Release-Action@v5
          with:
            title: ${{ github.ref }}
            tag: ${{ github.ref }}
            prerelease: false
